// @generated by P1 upgrade task
// Shared types for Triangle Black Portal

export interface ApiResponse<T = any> {
  data: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T = any> {
  items: T[];
  total: number;
  page: number;
  limit: number;
}

export interface BaseEntity {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Lead extends BaseEntity {
  company_name: string;
  contact_name: string;
  email: string;
  phone?: string;
  status: 'new' | 'qualified' | 'negotiation' | 'won' | 'lost';
  source?: string;
  notes?: string;
}

export interface WorkOrder extends BaseEntity {
  title: string;
  description?: string;
  status: 'open' | 'in_progress' | 'completed' | 'cancelled';
  priority: 'low' | 'medium' | 'high' | 'critical' | 'emergency';
  category?: string;
  location?: string;
  asset_id?: string;
  technician_id?: string;
  due_date?: string;
  estimated_hours?: number;
}

export interface Technician extends BaseEntity {
  name: string;
  email?: string;
  phone?: string;
  role?: string;
  specialization?: string;
  region?: string;
  is_active: boolean;
  current_assignments?: number;
  current_work_orders?: number;
}

export interface Asset extends BaseEntity {
  name: string;
  asset_type?: string;
  location?: string;
  status?: string;
  serial_number?: string;
  model?: string;
  manufacturer?: string;
}

export type Status = 'active' | 'inactive' | 'pending' | 'completed' |
  'failed' | 'new' | 'qualified' | 'negotiation' | 'won' | 'lost' |
  'open' | 'in_progress' | 'cancelled' | 'closed';

export type Priority = 'low' | 'medium' | 'high' | 'critical' | 'emergency';
