"""
V7-005 — KPI Registry API
Returns the machine-readable KPI registry.
Every KPI is documented with formula, confidence rules, and thresholds.
"""
from __future__ import annotations

KPI_REGISTRY = [
    {
        "kpi_id": "ohi",
        "label": "Operational Health Index",
        "endpoint": "/api/v1/executive-engine/health-score",
        "unit": "score",
        "range": [0, 100],
        "formula": "weighted_avg(WO_completion×0.25, PM_compliance×0.25, SLA×0.20, asset_health×0.15, supplier_score×0.15)",
        "source_tables": ["work_orders", "maintenance_plans", "assets", "suppliers"],
        "thresholds": {"excellent": 90, "good": 75, "warning": 60, "critical": 0},
        "target": 85,
        "confidence_note": "MEDIUM — limited by WO-asset linkage",
        "owner": "executive_engine",
    },
    {
        "kpi_id": "pm_compliance",
        "label": "PM Compliance Rate",
        "endpoint": "/api/v1/pm-engine/summary",
        "unit": "%",
        "range": [0, 100],
        "formula": "(total_plans - overdue_plans) / total_plans × 100",
        "source_tables": ["maintenance_plans"],
        "thresholds": {"excellent": 95, "good": 85, "warning": 70, "critical": 0},
        "target": 85,
        "confidence_note": "MEDIUM — 73.4% of plans have next_due_date",
        "owner": "pm_engine",
    },
    {
        "kpi_id": "mttr",
        "label": "Mean Time To Repair",
        "endpoint": "/api/v1/trend-engine/mttr",
        "unit": "hours",
        "range": [0, None],
        "formula": "AVG(completed_at - created_at) WHERE asset_id IS NOT NULL AND completed_at > created_at",
        "source_tables": ["work_orders"],
        "thresholds": {"emergency_target": 4, "critical_target": 8, "high_target": 24},
        "target": "< 24h for high priority",
        "confidence_note": "VERY_LOW — only 8.2% WO-asset linkage",
        "data_limitation": "91.8% of WOs excluded due to missing asset_id",
        "owner": "trend_engine",
    },
    {
        "kpi_id": "proactive_ratio",
        "label": "Proactive Maintenance Ratio",
        "endpoint": "/api/v1/trend-engine/proactive-ratio",
        "unit": "%",
        "range": [0, 100],
        "formula": "COUNT(type IN proactive_types) / COUNT(*) × 100",
        "source_tables": ["work_orders"],
        "thresholds": {"good": 70, "warning": 50, "critical": 0},
        "target": 70,
        "confidence_note": "MEDIUM — depends on WO type field population",
        "owner": "trend_engine",
    },
    {
        "kpi_id": "repeat_failure_rate",
        "label": "Repeat Failure Rate",
        "endpoint": "/api/v1/trend-engine/repeat-failures",
        "unit": "%",
        "range": [0, 100],
        "formula": "COUNT(assets with >= 3 WOs in 90 days) / COUNT(assets with any WO) × 100",
        "source_tables": ["work_orders"],
        "thresholds": {"good": 5, "warning": 10, "critical": 20},
        "target": "< 5%",
        "confidence_note": "VERY_LOW — limited by 8.2% WO-asset linkage",
        "owner": "trend_engine",
    },
    {
        "kpi_id": "wo_completion_rate",
        "label": "Work Order Completion Rate",
        "endpoint": "/api/v1/kpi-engine/dashboard",
        "unit": "%",
        "range": [0, 100],
        "formula": "COUNT(status='completed') / COUNT(*) × 100",
        "source_tables": ["work_orders"],
        "thresholds": {"good": 80, "warning": 60, "critical": 0},
        "target": 80,
        "confidence_note": "HIGH — all WOs included, no linkage dependency",
        "owner": "kpi_engine",
    },
    {
        "kpi_id": "ai_acceptance_rate",
        "label": "AI Recommendation Acceptance Rate",
        "endpoint": "/api/v1/recommendations/effectiveness",
        "unit": "%",
        "range": [0, 100],
        "formula": "COUNT(status='approved') / COUNT(*) × 100",
        "source_tables": ["recommendations"],
        "thresholds": {"good": 50, "warning": 20, "critical": 0},
        "target": 30,
        "confidence_note": "HIGH — all recommendations included",
        "owner": "recommendations",
    },
    {
        "kpi_id": "outcome_tracking",
        "label": "AI Outcome Tracking Coverage",
        "endpoint": "/api/v1/recommendations/effectiveness",
        "unit": "%",
        "range": [0, 100],
        "formula": "COUNT(outcomes) / COUNT(approved) × 100",
        "source_tables": ["recommendations", "recommendation_outcomes"],
        "thresholds": {"good": 50, "warning": 20, "critical": 0},
        "target": 20,
        "confidence_note": "HIGH — count-based",
        "owner": "recommendations",
    },
    {
        "kpi_id": "cost_avoidance_estimate",
        "label": "Estimated Annual Cost Avoidance",
        "endpoint": "/api/v1/roi/report",
        "unit": "EGP",
        "range": [0, None],
        "formula": "total_operational_spend × 0.10 (industry benchmark estimate)",
        "source_tables": ["purchase_orders", "invoices"],
        "thresholds": None,
        "target": None,
        "confidence_note": "LOW — estimate only, not measured outcome",
        "commercial_warning": "Must be labeled as 'potential avoidable cost' not 'guaranteed savings'",
        "owner": "roi_engine",
    },
    {
        "kpi_id": "wo_asset_linkage",
        "label": "Work Order → Asset Linkage",
        "endpoint": "/api/v1/data-quality/confidence-report",
        "unit": "%",
        "range": [0, 100],
        "formula": "COUNT(asset_id IS NOT NULL) / COUNT(*) × 100",
        "source_tables": ["work_orders"],
        "thresholds": {"good": 85, "warning": 60, "critical": 0},
        "target": 85,
        "confidence_note": "HIGH — direct count, no estimation",
        "current_value": 8.2,
        "current_status": "CRITICAL — below target",
        "owner": "data_quality",
    },
]


def get_registry() -> dict:
    """Return the complete KPI registry."""
    return {
        "registry_version": "7.0",
        "kpi_count": len(KPI_REGISTRY),
        "governance_rules": [
            "No KPI may be presented without disclosing data coverage",
            "No KPI may claim HIGH confidence without >= 85% coverage",
            "Cost avoidance estimates must be labeled as estimates",
            "KPIs with < 30% coverage must show VERY_LOW confidence",
            "Every new KPI must be registered before deployment",
        ],
        "kpis": KPI_REGISTRY,
    }
