services:
  backend:
    build: .
    env_file: .env.production
    ports:
    - 8030:8030
  postgres:
    image: postgres:15
    volumes:
    - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
version: '3.9'
volumes:
  pgdata: null
  tb_redis_data:
    driver: local
