import os, json, datetime, urllib.request, subprocess

LOG    = '/home/amr/AI-COMPANY-OS/tasks/logs/task_08.log'
ROOT   = '/home/amr/AI-COMPANY-OS'
OLLAMA = 'http://localhost:11434/api/generate'
MODEL  = 'llama3.2:3b'
results = {'created': [], 'warnings': []}

def log(msg):
    ts = datetime.datetime.now().strftime('%H:%M:%S')
    out = '[' + ts + '] ' + str(msg)
    print(out, flush=True)
    open(LOG, 'a').write(out + chr(10))

def ask(prompt, timeout=90):
    data = json.dumps({
        'model': MODEL, 'prompt': prompt,
        'stream': False, 'keep_alive': '10m',
        'options': {'num_predict': 400, 'temperature': 0.5},
    }).encode()
    req = urllib.request.Request(
        OLLAMA, data=data,
        headers={'Content-Type': 'application/json'}, method='POST'
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return json.loads(r.read()).get('response', '')
    except Exception as e:
        return 'Error: ' + str(e)

def psql(q, db='ai_company_os'):
    env = {**os.environ, 'PGPASSWORD': 'postgres'}
    r = subprocess.run(
        ['psql','-U','postgres','-d',db,'-h','localhost',
         '-P','pager=off','-t','-A','-c', q],
        capture_output=True, text=True, env=env, timeout=10
    )
    return r.stdout.strip()

log('TASK 08 START — CEO Daily Digest')
today = datetime.date.today().strftime('%Y-%m-%d')

# Gather real data
log('Gathering system data...')
tasks_done    = psql("SELECT count(*) FROM tasks WHERE status='completed';")
tasks_pending = psql("SELECT count(*) FROM tasks WHERE status='pending';")
tasks_failed  = psql("SELECT count(*) FROM tasks WHERE status='failed';")
agent_count   = psql('SELECT count(*) FROM agents;')
memory_count  = psql('SELECT count(*) FROM memories;')
tb_leads      = psql("SELECT count(*) FROM leads;", db='triangle_black')
tb_wos        = psql("SELECT count(*) FROM work_orders;", db='triangle_black')
tb_qualified  = psql("SELECT count(*) FROM leads WHERE status='qualified';", db='triangle_black')
tb_negotiation= psql("SELECT count(*) FROM leads WHERE status='negotiation';", db='triangle_black')
log('  Tasks: done=' + tasks_done + ' pending=' + tasks_pending + ' failed=' + tasks_failed)
log('  TB: leads=' + tb_leads + ' WOs=' + tb_wos)

# Generate CEO insights
log('Generating CEO insights with ' + MODEL + '...')
insight = ask(
    'You are the CEO of Triangle Black — hotel engineering SaaS company in Egypt. ' +
    'Date: ' + today + '. ' +
    'System status: ' +
    str(tasks_done) + ' tasks completed, ' +
    str(tasks_pending) + ' tasks pending, ' +
    str(tasks_failed) + ' tasks failed. ' +
    'Business pipeline: ' +
    str(tb_leads) + ' total leads, ' +
    str(tb_qualified) + ' qualified, ' +
    str(tb_negotiation) + ' in negotiation. ' +
    str(tb_wos) + ' work orders. ' +
    'AI agents: ' + str(agent_count) + ' active, ' +
    str(memory_count) + ' memories stored. ' +
    'Give a concise daily briefing: priorities, risks, and top 3 actions for today.'
)
log('  Insight: ' + str(len(insight.split())) + ' words')

# Save digest to file
digest_dir = ROOT + '/reports/daily'
os.makedirs(digest_dir, exist_ok=True)
digest_file = digest_dir + '/ceo-digest-' + today + '.md'

content = '# CEO Daily Digest' + chr(10)
content += '**Date:** ' + today + chr(10)
content += '**Generated:** ' + str(datetime.datetime.now().strftime('%H:%M')) + chr(10) + chr(10)
content += '---' + chr(10) + chr(10)
content += '## System KPIs' + chr(10)
content += '| Metric | Value |' + chr(10)
content += '|--------|-------|' + chr(10)
content += '| Tasks Completed | ' + tasks_done + ' |' + chr(10)
content += '| Tasks Pending | ' + tasks_pending + ' |' + chr(10)
content += '| Tasks Failed | ' + tasks_failed + ' |' + chr(10)
content += '| Active Agents | ' + agent_count + ' |' + chr(10)
content += '| Agent Memories | ' + memory_count + ' |' + chr(10) + chr(10)
content += '## Business Pipeline (Triangle Black)' + chr(10)
content += '| Metric | Value |' + chr(10)
content += '|--------|-------|' + chr(10)
content += '| Total Leads | ' + tb_leads + ' |' + chr(10)
content += '| Qualified | ' + tb_qualified + ' |' + chr(10)
content += '| In Negotiation | ' + tb_negotiation + ' |' + chr(10)
content += '| Work Orders | ' + tb_wos + ' |' + chr(10) + chr(10)
content += '## CEO AI Insights' + chr(10) + chr(10)
content += insight + chr(10) + chr(10)
content += '---' + chr(10)
content += '*Generated by AI Company OS CEO Agent*' + chr(10)

with open(digest_file, 'w') as f: f.write(content)
log('  Digest saved: ' + digest_file)
results['created'].append(digest_file)

# Save to memories table for agent context
memory_content = '[CEO DIGEST ' + today + '] ' + insight[:500]
env = {**os.environ, 'PGPASSWORD': 'postgres'}
subprocess.run(
    ['psql','-U','postgres','-d','ai_company_os','-h','localhost',
     '-c', "INSERT INTO memories(agent_name,content,memory_type,created_at,updated_at) VALUES('ceo','" + memory_content.replace("'","''") + "','long_term',NOW(),NOW()) ON CONFLICT DO NOTHING;"],
    capture_output=True, text=True, env=env, timeout=5
)
log('  Saved to agent memories')

# Create cron helper
cron_helper = ROOT + '/tasks/hub/setup_ceo_cron.sh'
cron_lines = [
    '#!/bin/bash',
    '# Run CEO digest daily at 8am',
    '# Add to crontab: crontab -e',
    '# Then add this line:',
    '# 0 8 * * * cd /home/amr/AI-COMPANY-OS && python3 tasks/hub/task_08_ceo_digest.py >> /tmp/ceo-digest.log 2>&1',
    '',
    '(crontab -l 2>/dev/null; echo "0 8 * * * cd /home/amr/AI-COMPANY-OS && python3 tasks/hub/task_08_ceo_digest.py >> /tmp/ceo-digest.log 2>&1") | crontab -',
    'echo "CEO digest cron added — runs daily at 8:00 AM"',
    'crontab -l | tail -3',
]
with open(cron_helper, 'w') as f: f.write(chr(10).join(cron_lines))
os.chmod(cron_helper, 0o755)
log('  Cron helper: bash ' + cron_helper)

import json as _json
log('=' * 40)
log('TASK 08 COMPLETE')
log('  Created: ' + str(len(results['created'])))
log('  Run daily: python3 tasks/hub/task_08_ceo_digest.py')
log('  Auto-schedule: bash tasks/hub/setup_ceo_cron.sh')
with open('/home/amr/AI-COMPANY-OS/tasks/logs/task_08_result.json','w') as f:
    _json.dump(results, f, indent=2)