// Triangle Black - Center Sub-Navigation Data
// One entry per enterprise center

export const CENTER_SUB_NAV: Record<string, { label: string; href: string }[]> = {
  operations: [
    { label: "Overview",         href: "/operations" },
    { label: "Work Orders",      href: "/operations/work-orders" },
    { label: "Dispatch",         href: "/operations/dispatch" },
    { label: "Calendar",         href: "/operations/calendar" },
    { label: "Technicians",      href: "/operations/technicians" },
    { label: "Service Requests", href: "/operations/service-requests" },
    { label: "SLA Review",       href: "/operations/sla-review" },
    { label: "Workflows",        href: "/operations/workflows" },
    { label: "Workbench",        href: "/operations/workbench" },
  ],
  maintenance: [
    { label: "Overview",     href: "/maintenance" },
    { label: "Assets",       href: "/maintenance/assets" },
    { label: "Asset Tree",   href: "/maintenance/asset-tree" },
    { label: "PM Plans",     href: "/maintenance/pm-plans" },
    { label: "Schedule",     href: "/maintenance/schedule" },
    { label: "Intelligence", href: "/maintenance/intelligence" },
    { label: "Actions",      href: "/maintenance/actions" },
    { label: "Costs",        href: "/maintenance/costs/review" },
    { label: "Downtime",     href: "/maintenance/downtime/review" },
  ],
  "supply-chain": [
    { label: "Overview",          href: "/supply-chain" },
    { label: "Inventory",         href: "/supply-chain/inventory" },
    { label: "Warehouses",        href: "/warehouses" },
    { label: "Purchase Requests", href: "/supply-chain/purchase-requests" },
    { label: "Purchase Orders",   href: "/supply-chain/purchase-orders" },
    { label: "Suppliers",         href: "/supply-chain/suppliers" },
    { label: "RFQs",              href: "/supply-chain/rfqs" },
    { label: "Goods Receipts",    href: "/supply-chain/goods-receipts" },
    { label: "Spend Analysis",    href: "/supply-chain/spend" },
    { label: "Workbench",         href: "/supply-chain/workbench" },
  ],
  commercial: [
    { label: "Overview",    href: "/commercial" },
    { label: "Leads",       href: "/leads" },
    { label: "Customers",   href: "/customers" },
    { label: "Contracts",   href: "/contracts" },
    { label: "Invoices",    href: "/invoices" },
    { label: "Quotes",      href: "/quotes" },
    { label: "Pipeline",    href: "/commercial/pipeline" },
    { label: "Workbench",   href: "/commercial/workbench" },
  ],
  executive: [
    { label: "Overview",     href: "/executive" },
    { label: "Intelligence", href: "/executive/intelligence" },
    { label: "Portfolio",    href: "/executive/portfolio" },
    { label: "Risks",        href: "/executive/risks" },
    { label: "Exceptions",   href: "/executive/exceptions" },
    { label: "Daily Review", href: "/executive/daily-review" },
    { label: "Reports",      href: "/executive/reports" },
    { label: "Workbench",    href: "/executive/workbench" },
  ],
  engineering: [
    { label: "Overview",    href: "/engineering" },
    { label: "AI Assistant",href: "/engineering/ai" },
    { label: "Intelligence",href: "/engineering/intelligence" },
    { label: "Actions",     href: "/engineering/actions" },
    { label: "Review",      href: "/engineering/review" },
  ],
  analytics: [
    { label: "Overview",    href: "/analytics" },
    { label: "Scorecards",  href: "/analytics/scorecards" },
    { label: "SLA Reports", href: "/analytics/sla" },
  ],
  "projects-center": [
    { label: "Overview",    href: "/projects-center" },
    { label: "Actions",     href: "/projects-center/actions" },
    { label: "Intelligence",href: "/projects-center/intelligence" },
    { label: "Review",      href: "/projects-center/review" },
    { label: "Schedule",    href: "/projects-center/review/schedule" },
  ],
  customers: [
    { label: "Overview", href: "/customers" },
    { label: "360 View", href: "/customers/360" },
    { label: "Review",   href: "/customers/review" },
  ],
  administration: [
    { label: "Overview",            href: "/administration" },
    { label: "Hotels & Properties", href: "/administration/hotels" },
    { label: "Notification Rules",  href: "/admin/notification-rules" },
    { label: "User Management",     href: "/administration/users" },
    { label: "Audit Log",           href: "/administration/audit" },
    { label: "Profile",             href: "/profile" },
    { label: "Settings",            href: "/settings" },
  ],
};
