"use client";

import { PageWrapper, PageHeader, SectionCard, EmptyState, Button } from "@/components/ui";
import React, { useState } from "react";

const NotificationRulesPage = () => {
  const [ruleActive, setRuleActive] = useState({
    "Critical Work Orders": true,
    "SLA Breach Risk": true,
    "Inventory Below Minimum": true,
    "PM Plan Overdue": true,
    "Contracts Expiring": true,
  });

  const toggleRule = (ruleName: string) => {
    setRuleActive((prev) => ({ ...prev, [ruleName]: !prev[ruleName] }));
  };

  return (
    <PageWrapper>
      <PageHeader title="Notification Rules" badge="Beta">
        Notifications are generated by the Triangle Black AI Signals Engine
      </PageHeader>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {Object.entries(ruleActive).map(([ruleName, isActive]) => (
          <SectionCard key={ruleName} title={ruleName}>
            <p>Trigger: {ruleName === "SLA Breach Risk" ? "compliance < 80%" : ruleName === "Inventory Below Minimum" ? "stock < min" : ruleName === "PM Plan Overdue" ? "next_due_date passed" : ruleName === "Contracts Expiring" ? "30 days before end_date" : ""}</p>
            <p>Channel: {ruleName === "Critical Work Orders" ? "Email + Signal" : ruleName === "SLA Breach Risk" ? "Signal + Badge" : ruleName === "Inventory Below Minimum" ? "Signal" : ruleName === "PM Plan Overdue" ? "Signal" : ruleName === "Contracts Expiring" ? "Signal" : ""}</p>
            <Button onClick={() => toggleRule(ruleName)} variant={isActive ? "outline" : "primary"}>{isActive ? "Deactivate" : "Activate"}</Button>
          </SectionCard>
        ))}
      </div>
      <EmptyState title="No rules configured yet">
        <Button href="/alerts">View Live Signals</Button>
      </EmptyState>
    </PageWrapper>
  );
};

export default NotificationRulesPage;