"use client"; // @ts-nocheck
// @ts-nocheck

import { useQuery } from "@tanstack/react-query";
import { PageWrapper, PageHeader, SectionCard, MetricStrip, StatusBadge, LoadingState, EmptyState } from "@/components/ui";

const BACK = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8030";


const fetchSignals = async () => {
  const response = await fetch(`${BACK}/api/v1/ai/signals`, { credentials: "include" });
  if (!response.ok) return [];
  return response.json();
};

const fetchCostsSummary = async () => {
  const response = await fetch(`${BACK}/api/v1/ai/analytics/costs/summary`, { credentials: "include" });
  if (!response.ok) return [];
  return response.json();
};

const fetchSLA = async () => {
  const response = await fetch(`${BACK}/api/v1/ai/analytics/sla`, { credentials: "include" });
  if (!response.ok) return [];
  return response.json();
};

const fetchKPIsLive = async () => {
  const response = await fetch(`${BACK}/api/v1/ai/analytics/kpis/live`, { credentials: "include" });
  if (!response.ok) return [];
  return response.json();
};

const PredictivePage = () => {
  const signalsQuery = useQuery(["signals"], fetchSignals, { refetchInterval: 30000 });
  const costsSummaryQuery = useQuery(["costsSummary"], fetchCostsSummary, { refetchInterval: 120000 });
  const slaQuery = useQuery(["sla"], fetchSLA, { refetchInterval: 120000 });
  const kpisLiveQuery = useQuery(["kpisLive"], fetchKPIsLive, { refetchInterval: 120000 });

  if (signalsQuery.isLoading || costsSummaryQuery.isLoading || slaQuery.isLoading || kpisLiveQuery.isLoading) return <LoadingState />;

  if (signalsQuery.isError || costsSummaryQuery.isError || slaQuery.isError || kpisLiveQuery.isError) return <EmptyState />;

  const { signals } = signalsQuery.data;
  const { totalPredictions, highRisk, mediumRisk, monitoring } = costsSummaryQuery.data;
  const { sla } = slaQuery.data;
  const { wos } = kpisLiveQuery.data;

  return (
    <PageWrapper>
      <PageHeader title="Predictive Alerts" />
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <MetricStrip
          title="Total Predictions"
          value={totalPredictions}
          icon="/icons/predictions.svg"
        />
        <MetricStrip
          title="High Risk"
          value={highRisk}
          icon="/icons/high-risk.svg"
        />
        <MetricStrip
          title="Medium Risk"
          value={mediumRisk}
          icon="/icons/medium-risk.svg"
        />
        <MetricStrip
          title="Monitoring"
          value={monitoring}
          icon="/icons/monitoring.svg"
        />
      </div>
      <SectionCard title="Predictive Risk Cards">
        {(signals || []).sort((a: any, b: any) => (b.priority > a.priority ? -1 : 1)).map(signal => (
          <div key={signal.id} className="p-4 border-b last:border-b-0">
            <StatusBadge status={signal.priority} />
            <h3>{signal.title}</h3>
            <p>{signal.context}</p>
            <p><strong>Impact:</strong> {signal.impact}</p>
            <p><strong>Action:</strong> {signal.recommended_action}</p>
            <p><strong>Timeframe:</strong> {signal.priority === "critical" ? "Immediate" : signal.priority === "high" ? "This Week" : "This Month"}</p>
          </div>
        ))}
      </SectionCard>
      <SectionCard title="Forecast">
        <p><strong>SLA:</strong> At current rate, SLA will remain below 30% for next 30 days unless critical WOs are resolved</p>
        <p><strong>Cost:</strong> WO costs trending stable at avg 11,565 EGP per WO</p>
        <p><strong>Capacity:</strong> Technician utilization at 34% — capacity available for 16 more WOs</p>
      </SectionCard>
      <div className="text-center mt-8">
        <p className="text-sm text-gray-500">Predictions generated by Triangle Black AI Signals Engine v1.0</p>
      </div>
    </PageWrapper>
  );
};

export default PredictivePage;