"""
app/models/db/learning_insight.py
────────────────────────────────────────────────────────────────
Stores learning insights generated by the Learning Engine.
Append-only. New run produces new insights — old ones kept for history.
"""

from __future__ import annotations

from sqlalchemy import String, Text, Float, Integer, JSON, Index
from sqlalchemy.orm import Mapped, mapped_column

from db.base import Base, TimestampMixin


class LearningInsightRecord(Base, TimestampMixin):
    __tablename__ = "learning_insights"

    id: Mapped[int] = mapped_column(
        Integer, primary_key=True, autoincrement=True
    )

    insight_type: Mapped[str] = mapped_column(
        String(50), nullable=False
    )
    # model_performance | prompt_quality | agent_pattern |
    # failure_pattern | speed_pattern | improvement

    agent_name: Mapped[str | None] = mapped_column(
        String(100), nullable=True
    )
    model: Mapped[str | None] = mapped_column(
        String(100), nullable=True
    )

    title:          Mapped[str]   = mapped_column(String(255), nullable=False)
    description:    Mapped[str]   = mapped_column(Text, nullable=False)
    recommendation: Mapped[str]   = mapped_column(Text, nullable=False)

    evidence:    Mapped[dict | None] = mapped_column(JSON, nullable=True)
    confidence:  Mapped[float]       = mapped_column(Float, default=0.5)
    priority:    Mapped[int]         = mapped_column(Integer, default=3)
    # 1=urgent, 2=high, 3=medium, 4=low, 5=informational

    # Was this insight acted on?
    applied: Mapped[bool] = mapped_column(default=False)

    __table_args__ = (
        Index("ix_learning_insights_type",       "insight_type"),
        Index("ix_learning_insights_agent",      "agent_name"),
        Index("ix_learning_insights_priority",   "priority"),
        Index("ix_learning_insights_created_at", "created_at"),
    )

    def __repr__(self) -> str:
        return (
            f"<LearningInsight id={self.id} "
            f"type={self.insight_type!r} "
            f"priority={self.priority}>"
        )
