"""
app/models/db/prompt_version.py
────────────────────────────────────────────────────────────────
Stores all versions of every agent's system prompt.
Append-only audit trail — old versions are never deleted.

Version lifecycle:
  1  → created (first save)
  2  → improved (auto-generated by PromptOptimizer)
  N  → improved again

The active version for an agent is the one with is_active=True.
Rolling back = set previous version is_active=True.
"""

from __future__ import annotations

from sqlalchemy import String, Text, Float, Integer, JSON, Index, Boolean
from sqlalchemy.orm import Mapped, mapped_column

from db.base import Base, TimestampMixin


class PromptVersion(Base, TimestampMixin):
    __tablename__ = "prompt_versions"

    id: Mapped[int] = mapped_column(
        Integer, primary_key=True, autoincrement=True
    )

    agent_name: Mapped[str] = mapped_column(String(100), nullable=False)
    version:    Mapped[int] = mapped_column(Integer,     nullable=False)
    content:    Mapped[str] = mapped_column(Text,        nullable=False)

    # What triggered this version
    source: Mapped[str] = mapped_column(
        String(50), nullable=False, default="manual"
    )
    # manual | auto_improvement | rollback | initial

    # Quality metrics at time of creation
    quality_score_before: Mapped[float | None] = mapped_column(Float, nullable=True)
    quality_score_after:  Mapped[float | None] = mapped_column(Float, nullable=True)

    # What changed
    change_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    improvement_hints: Mapped[list | None] = mapped_column(JSON, nullable=True)

    # Active flag
    is_active: Mapped[bool] = mapped_column(Boolean, default=False)

    __table_args__ = (
        Index("ix_prompt_versions_agent",      "agent_name"),
        Index("ix_prompt_versions_active",     "is_active"),
        Index("ix_prompt_versions_created_at", "created_at"),
    )

    def __repr__(self) -> str:
        return (
            f"<PromptVersion agent={self.agent_name!r} "
            f"v{self.version} active={self.is_active}>"
        )
