"use client"; // @ts-nocheck

import { useQuery } from "@tanstack/react-query";
import { PageWrapper, PageHeader, SectionCard, MetricStrip, StatusBadge, LoadingState, EmptyState } from "@/components/ui";
import Link from "next/link";

const fetchSignals = async () => {
  const response = await fetch("/api/v1/ai/signals", { credentials: "include" });
  if (!response.ok) throw new Error("Failed to fetch signals");
  return response.json();
};

const fetchKpis = async () => {
  const response = await fetch("/api/v1/ai/analytics/kpis/live", { credentials: "include" });
  if (!response.ok) throw new Error("Failed to fetch KPIs");
  return response.json();
};

const RecommendationsPage = () => {
  const signalsQuery = useQuery(["signals"], fetchSignals, { refetchInterval: 60000 });
  const kpisQuery = useQuery(["kpis"], fetchKpis, { refetchInterval: 60000 });

  if (signalsQuery.isLoading || kpisQuery.isLoading) return <LoadingState />;

  if (signalsQuery.isError || kpisQuery.isError) return <p>Error fetching data</p>;

  const signals = signalsQuery.data.filter(signal => signal.recommended_action);
  const totalRecommendations = signals.length;
  const criticalActions = signals.filter(signal => signal.priority === "critical").length;
  const highPriority = signals.filter(signal => signal.priority === "high").length;

  if (totalRecommendations === 0) {
    return (
      <PageWrapper>
        <EmptyState title="All systems optimal — no recommendations at this time" />
      </PageWrapper>
    );
  }

  const sortedSignals = [...signals].sort((a, b) => {
    if (a.priority !== b.priority) return a.priority === "critical" ? -1 : 1;
    return 0;
  });

  return (
    <PageWrapper>
      <PageHeader title="AI Recommendations" />
      <SectionCard>
        <MetricStrip
          metrics={[
            { label: "Total Recommendations", value: totalRecommendations },
            { label: "Critical Actions", value: criticalActions, color: "red" },
            { label: "High Priority", value: highPriority, color: "amber" },
            { label: "Completed", value: 0 }
          ]}
        />
      </SectionCard>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {sortedSignals.map(signal => (
          <SectionCard key={signal.id}>
            <StatusBadge label={signal.priority} color={signal.priority === "critical" ? "red" : signal.priority === "high" ? "amber" : "blue"} />
            <h2 className="font-bold">{signal.title}</h2>
            <p>{signal.recommended_action}</p>
            <StatusBadge label={signal.category} />
            <Link href={`/operations/workbench`} passHref legacyBehavior>
              <a className="mt-4 block text-blue-500 hover:underline">Take Action</a>
            </Link>
          </SectionCard>
        ))}
      </div>
      <footer className="text-center mt-8">
        Recommendations generated by Triangle Black AI Engine — refreshed every 60s
      </footer>
    </PageWrapper>
  );
};

export default RecommendationsPage;