#!/bin/bash
# Run this to change PostgreSQL password
# Generated by task_07

NEW_PASS="hMdzkPpgUz7qvu46AHex"

echo "Changing PostgreSQL password..."
docker exec -i ai-postgres psql -U postgres -c "ALTER USER postgres PASSWORD '$NEW_PASS';"

# Update all DATABASE_URL in .env files
find /home/amr/AI-COMPANY-OS -name ".env" -not -path "*/.venv/*" -not -path "*/node_modules/*" | while read f; do
  sed -i "s|postgresql+psycopg2://postgres:postgres@|postgresql+psycopg2://postgres:${NEW_PASS}@|g" "$f"
  sed -i "s|POSTGRES_PASSWORD=postgres|POSTGRES_PASSWORD=${NEW_PASS}|g" "$f"
  echo "Updated: $f"
done

echo "Done! Restart services: bash /home/amr/AI-COMPANY-OS/START-SAFE.sh"