import os, secrets, string, datetime, json, glob, subprocess

LOG  = '/home/amr/AI-COMPANY-OS/tasks/logs/task_07.log'
ROOT = '/home/amr/AI-COMPANY-OS'
results = {'generated': [], 'updated': [], 'warnings': []}

def log(msg):
    ts = datetime.datetime.now().strftime('%H:%M:%S')
    out = '[' + ts + '] ' + str(msg)
    print(out, flush=True)
    open(LOG, 'a').write(out + chr(10))

def gen_secret(length=32):
    chars = string.ascii_letters + string.digits + '!@#$%^&*'
    return ''.join(secrets.choice(chars) for _ in range(length))

def gen_password(length=20):
    chars = string.ascii_letters + string.digits
    return ''.join(secrets.choice(chars) for _ in range(length))

log('TASK 07 START — Generate Real Secrets')

# Generate secrets
NEW_PG_PASS   = gen_password(20)
NEW_SECRET    = gen_secret(48)
NEW_TB_SECRET = gen_secret(48)
log('  Generated new PostgreSQL password: ' + NEW_PG_PASS[:4] + '****')
log('  Generated new SECRET_KEY: ' + NEW_SECRET[:8] + '****')
log('  Generated new TB_SECRET_KEY: ' + NEW_TB_SECRET[:8] + '****')

# Save secrets to a SECURE file (not in git)
secrets_file = os.path.expanduser('~/.ai-company-os-secrets')
secret_content = [
    '# AI Company OS — Generated Secrets',
    '# Generated: ' + str(datetime.datetime.now()),
    '# KEEP THIS FILE SAFE — do not share or commit',
    '',
    'NEW_POSTGRES_PASSWORD=' + NEW_PG_PASS,
    'NEW_SECRET_KEY=' + NEW_SECRET,
    'NEW_TB_SECRET_KEY=' + NEW_TB_SECRET,
    '',
    '# To apply:',
    '# 1. Update .env files with these values',
    '# 2. Restart all services',
    '# 3. Change PostgreSQL password in Docker',
]
with open(secrets_file, 'w') as f:
    os.chmod(secrets_file, 0o600)
    f.write(chr(10).join(secret_content))
log('  Secrets saved to: ' + secrets_file + ' (chmod 600)')
results['generated'].append('secrets file: ' + secrets_file)

# Update main .env
log('Updating .env files...')
main_env = ROOT + '/.env'
if os.path.exists(main_env):
    with open(main_env) as f: content = f.read()
    import shutil
    shutil.copy2(main_env, main_env + '.bak')
    # Replace weak SECRET_KEY only (keep DB password for now - needs docker cmd)
    import re
    new_content = re.sub(
        r'SECRET_KEY=.*',
        'SECRET_KEY=' + NEW_SECRET,
        content
    )
    with open(main_env, 'w') as f: f.write(new_content)
    results['updated'].append('.env SECRET_KEY updated')
    log('  OK .env SECRET_KEY updated')

# Update AI Engine .env
engine_env = ROOT + '/07-AI-ENGINE/.env'
if os.path.exists(engine_env):
    with open(engine_env) as f: content = f.read()
    shutil.copy2(engine_env, engine_env + '.bak')
    new_content = re.sub(r'SECRET_KEY=.*', 'SECRET_KEY=' + NEW_SECRET, content)
    with open(engine_env, 'w') as f: f.write(new_content)
    results['updated'].append('07-AI-ENGINE/.env SECRET_KEY updated')
    log('  OK 07-AI-ENGINE/.env updated')

# Update TB Admin .env
tb_env = ROOT + '/11-WORKSPACES/triangle-black/.env'
if os.path.exists(tb_env):
    with open(tb_env) as f: content = f.read()
    shutil.copy2(tb_env, tb_env + '.bak')
    new_content = re.sub(r'TB_SECRET_KEY=.*', 'TB_SECRET_KEY=' + NEW_TB_SECRET, content)
    with open(tb_env, 'w') as f: f.write(new_content)
    results['updated'].append('TB .env TB_SECRET_KEY updated')
    log('  OK TB .env updated')

# Note: PostgreSQL password change needs docker exec
log('')
log('MANUAL STEP REQUIRED:')
log('  To change PostgreSQL password run these 2 commands:')
log('  1. docker exec -it ai-postgres psql -U postgres -c "ALTER USER postgres PASSWORD ' + chr(39) + NEW_PG_PASS + chr(39) + ';"')
log('  2. Then update DATABASE_URL in all .env files')
log('  New password saved in: ' + secrets_file)

# Write change_pg_password.sh helper
helper = ROOT + '/tasks/security/change_pg_password.sh'
helper_lines = [
    '#!/bin/bash',
    '# Run this to change PostgreSQL password',
    '# Generated by task_07',
    '',
    'NEW_PASS="' + NEW_PG_PASS + '"',
    '',
    'echo "Changing PostgreSQL password..."',
    'docker exec -i ai-postgres psql -U postgres -c "ALTER USER postgres PASSWORD ' + chr(39) + '$NEW_PASS' + chr(39) + ';"',
    '',
    '# Update all DATABASE_URL in .env files',
    'find /home/amr/AI-COMPANY-OS -name ".env" -not -path "*/.venv/*" -not -path "*/node_modules/*" | while read f; do',
    '  sed -i "s|postgresql+psycopg2://postgres:postgres@|postgresql+psycopg2://postgres:${NEW_PASS}@|g" "$f"',
    '  sed -i "s|POSTGRES_PASSWORD=postgres|POSTGRES_PASSWORD=${NEW_PASS}|g" "$f"',
    '  echo "Updated: $f"',
    'done',
    '',
    'echo "Done! Restart services: bash /home/amr/AI-COMPANY-OS/START-SAFE.sh"',
]
with open(helper, 'w') as f:
    f.write(chr(10).join(helper_lines))
os.chmod(helper, 0o700)
log('  Helper script: ' + helper)
log('  Run when ready: bash ' + helper)

import json
log('=' * 40)
log('TASK 07 COMPLETE')
log('  Generated: ' + str(len(results['generated'])))
log('  Updated:   ' + str(len(results['updated'])))
for u in results['updated']: log('  OK ' + u)
with open('/home/amr/AI-COMPANY-OS/tasks/logs/task_07_result.json','w') as f:
    json.dump(results, f, indent=2)