"""
app/templates/scaffold.py
────────────────────────────────────────────────────────────────
Project Scaffolding Engine.

Takes a template and a project name, creates the full
directory structure, generates initial files, runs setup
commands, and queues agent tasks to complete the project.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from pathlib import Path

from templates.library import ProjectTemplate, get_template

log = logging.getLogger(__name__)

PROJECTS_ROOT = Path.home() / "AI" / "projects" / "generated"


@dataclass
class ScaffoldResult:
    """Result of scaffolding a project."""
    success:          bool
    project_path:     str
    files_created:    list[str]
    dirs_created:     list[str]
    setup_results:    list[str]
    agent_tasks:      list[str]
    error:            str | None = None


class ProjectScaffold:

    def scaffold(
        self,
        template_id:   str,
        project_name:  str,
        description:   str   = "",
        output_dir:    str | None = None,
        run_install:   bool  = False,
        queue_tasks:   bool  = True,
    ) -> ScaffoldResult:
        """
        Create a complete project from a template.

        Args:
            template_id:  Template to use (from library)
            project_name: Name of the project
            description:  What the project does
            output_dir:   Where to create it (default: ~/AI/projects/generated/)
            run_install:  Run install commands after scaffold
            queue_tasks:  Queue agent tasks in background task system
        """
        template = get_template(template_id)
        if not template:
            return ScaffoldResult(
                success=False,
                project_path="",
                files_created=[],
                dirs_created=[],
                setup_results=[],
                agent_tasks=[],
                error=f"Template {template_id!r} not found",
            )

        # Resolve output path
        base_dir = Path(output_dir) if output_dir else PROJECTS_ROOT
        project_path = base_dir / project_name.lower().replace(" ", "-")
        project_path.mkdir(parents=True, exist_ok=True)

        files_created:   list[str] = []
        dirs_created:    list[str] = []
        setup_results:   list[str] = []

        # Template variables
        vars_map = {
            "{project_name}": project_name,
            "{description}":  description or f"{project_name} — generated by AI Company OS",
        }

        # Create directories
        for directory in template.directories:
            dir_path = project_path / self._fill(directory, vars_map)
            dir_path.mkdir(parents=True, exist_ok=True)
            dirs_created.append(str(dir_path.relative_to(project_path)))

        # Create files
        for file_template in template.files:
            rel_path = self._fill(file_template.path, vars_map)
            full_path = project_path / rel_path
            full_path.parent.mkdir(parents=True, exist_ok=True)

            content = self._fill(file_template.content, vars_map)
            full_path.write_text(content, encoding="utf-8")
            files_created.append(rel_path)

        # Run install commands
        if run_install:
            from tools.shell import shell_tool
            for cmd in template.install_cmds:
                filled_cmd = self._fill(cmd, vars_map)
                log.info("Running: %s", filled_cmd)
                result = shell_tool.run(
                    command=filled_cmd,
                    working_dir=str(project_path),
                    timeout=120,
                )
                setup_results.append(
                    f"{'✅' if result.success else '❌'} {filled_cmd}"
                )

        # Queue agent tasks
        if queue_tasks and template.agent_tasks:
            self._queue_agent_tasks(
                project_name=project_name,
                project_path=str(project_path),
                tasks=template.agent_tasks,
            )

        log.info(
            "Scaffolded %s: %d dirs, %d files",
            project_name, len(dirs_created), len(files_created),
        )

        return ScaffoldResult(
            success=True,
            project_path=str(project_path),
            files_created=files_created,
            dirs_created=dirs_created,
            setup_results=setup_results,
            agent_tasks=template.agent_tasks,
        )

    def _fill(self, template_str: str, vars_map: dict) -> str:
        result = template_str
        for placeholder, value in vars_map.items():
            result = result.replace(placeholder, value)
        return result

    def _queue_agent_tasks(
        self,
        project_name: str,
        project_path: str,
        tasks:        list[str],
    ) -> None:
        """Queue agent tasks in the background task system."""
        try:
            from tasks.queue import task_queue
            from tasks.handlers import run_project_task

            combined_goal = (
                f"Complete the scaffolded {project_name} project at {project_path}.\n\n"
                f"Complete these tasks in order:\n"
                + "\n".join(f"{i+1}. {t}" for i, t in enumerate(tasks))
            )

            task_queue.submit(
                task_type="project_run",
                task_name=f"Complete: {project_name}",
                params={
                    "name":  f"Complete {project_name}",
                    "goal":  combined_goal,
                    "owner": "scaffold",
                },
                handler=run_project_task,
                submitted_by="scaffold",
            )
            log.info("Queued completion tasks for %s", project_name)

        except Exception as exc:
            log.warning("Could not queue tasks: %s", exc)


project_scaffold = ProjectScaffold()
