from __future__ import annotations
"""
Triangle Black Background Scheduler — Sprint 78
Runs periodic jobs for operational automation.
"Stub scheduler — install apscheduler to enable."
"""
import datetime
import logging

logger = logging.getLogger("tb.scheduler")

{"" if not has_aps else """
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.triggers.cron import CronTrigger

_scheduler: AsyncIOScheduler | None = None

def get_scheduler() -> AsyncIOScheduler:
    global _scheduler
    if _scheduler is None:
        _scheduler = AsyncIOScheduler(timezone="Africa/Cairo")
    return _scheduler
"""}

def start_scheduler(app=None):
    """Start background scheduler — called on FastAPI startup."""
    {"" if not has_aps else """
    scheduler = get_scheduler()

    # Job 1: Auto-reorder check at 06:00 Cairo time daily
    scheduler.add_job(
        _job_check_reorder,
        CronTrigger(hour=6, minute=0, timezone="Africa/Cairo"),
        id="auto_reorder_check",
        replace_existing=True,
        name="Auto Reorder Check",
    )

    # Job 2: Critical WO alert check every 30 minutes
    scheduler.add_job(
        _job_critical_wo_check,
        CronTrigger(minute="*/30"),
        id="critical_wo_check",
        replace_existing=True,
        name="Critical WO Alert Check",
    )

    # Job 3: Daily SLA report at 07:00
    scheduler.add_job(
        _job_daily_sla_report,
        CronTrigger(hour=7, minute=0, timezone="Africa/Cairo"),
        id="daily_sla_report",
        replace_existing=True,
        name="Daily SLA Report",
    )

    scheduler.start()
    logger.info("Triangle Black Scheduler started — 3 jobs registered")
    return scheduler
    """}
    logger.info("Scheduler initialized (stub mode — apscheduler not available)")
    return None

def stop_scheduler():
    {"" if not has_aps else """
    scheduler = get_scheduler()
    if scheduler and scheduler.running:
        scheduler.shutdown()
        logger.info("Scheduler stopped")
    """}
    pass

async def _job_check_reorder():
    """
    Daily auto-reorder job.
    Checks inventory items below minimum and creates PRs automatically.
    """
    try:
        from src.core.database import get_db
        db = next(get_db())
        from sqlalchemy import text

        # Find items below minimum
        rows = db.execute(text("""
            SELECT ii.id, ii.name, ii.hotel_id, ii.min_stock, ii.reorder_qty,
                   COALESCE(sb.quantity, 0) as current_stock
            FROM inventory_items ii
            LEFT JOIN stock_balances sb ON sb.item_id = ii.id
            WHERE COALESCE(sb.quantity, 0) <= ii.min_stock
        """)).fetchall()

        count = 0
        now = datetime.datetime.utcnow()
        import uuid

        for row in rows:
            item = dict(row._mapping) if hasattr(row, "_mapping") else {}
            qty = max(
                int(item.get("reorder_qty") or 0),
                int(item.get("min_stock") or 0) - int(item.get("current_stock") or 0)
            )
            if qty <= 0:
                continue
            try:
                db.execute(text("""
                    INSERT INTO purchase_requests
                        (id, hotel_id, title, description, status, requested_by,
                         required_date, created_at, updated_at)
                    VALUES (:id, :hotel_id, :title, :desc, 'submitted', 'scheduler',
                            :req_date, :now, :now)
                """), {{
                    "id":       str(uuid.uuid4()),
                    "hotel_id": item.get("hotel_id"),
                    "title":    f"SCHEDULED-REORDER: {{item.get('name')}} x{{qty}}",
                    "desc":     f"Auto-generated by daily scheduler. Stock: {{item.get('current_stock')}} Min: {{item.get('min_stock')}}",
                    "req_date": now + datetime.timedelta(days=7),
                    "now":      now,
                }})
                count += 1
            except Exception:
                pass

        if count > 0:
            db.commit()
        logger.info(f"Auto-reorder job: {{count}} PRs created")
        db.close()
    except Exception as e:
        logger.error(f"Auto-reorder job failed: {{e}}")

async def _job_critical_wo_check():
    """Check for critical unassigned WOs and log alerts."""
    try:
        from src.core.database import get_db
        from sqlalchemy import text
        db = next(get_db())
        rows = db.execute(text("""
            SELECT count(*) as cnt FROM work_orders
            WHERE priority = 'critical'
              AND status = 'open'
              AND technician_id IS NULL
              AND created_at < NOW() - INTERVAL '2 hours'
        """)).fetchone()
        cnt = int(dict(rows._mapping if hasattr(rows,"_mapping") else {{}}).get("cnt") or 0)
        if cnt > 0:
            logger.warning(f"ALERT: {{cnt}} critical WOs unassigned for >2 hours")
        db.close()
    except Exception as e:
        logger.error(f"Critical WO check failed: {{e}}")

async def _job_daily_sla_report():
    """Log daily SLA summary."""
    try:
        from src.core.database import get_db
        from sqlalchemy import text
        db = next(get_db())
        row = db.execute(text("""
            SELECT count(*) as total,
                   sum(CASE WHEN status IN ('completed','closed') THEN 1 ELSE 0 END) as done
            FROM work_orders
            WHERE created_at >= DATE_TRUNC('month', NOW())
        """)).fetchone()
        d = dict(row._mapping if hasattr(row,"_mapping") else {{}})
        total = int(d.get("total") or 0)
        done  = int(d.get("done") or 0)
        rate  = round(done/total*100, 1) if total > 0 else 0
        logger.info(f"Daily SLA Report: {{done}}/{{total}} WOs completed ({{rate}}%)")
        db.close()
    except Exception as e:
        logger.error(f"Daily SLA report failed: {{e}}")
